# Generated by Django 4.1.7 on 2023-08-13 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('정보공유', '정보공유'), ('소통해요', '소통해요'), ('칭찬해요', '칭찬해요'), ('나눔해요', '나눔해요')], default='정보공유', max_length=10, verbose_name='게시판 카테고리')),
                ('title', models.CharField(max_length=200, verbose_name='게시판 제목')),
                ('content', models.TextField(verbose_name='게시판 내용')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성 일시')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정 일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성 일시')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성 일시')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정 일시')),
                ('author', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('community_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.communityboard')),
            ],
        ),
        migrations.CreateModel(
            name='ComplainBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='민원 제목')),
                ('content', models.TextField(verbose_name='민원 내용')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성 일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.complainboard')),
            ],
        ),
    ]
