# Generated by Django 4.1.7 on 2023-07-26 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('정보공유', '정보공유'), ('소통해요', '소통해요'), ('칭찬해요', '칭찬해요'), ('나눔해요', '나눔해요')], default='정보공유', max_length=10, verbose_name='게시판 카테고리')),
                ('title', models.CharField(max_length=200, verbose_name='게시판 제목')),
                ('content', models.TextField(verbose_name='게시판 내용')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성 일시')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정 일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성 일시')),
            ],
        ),
        migrations.CreateModel(
            name='Sound_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dong', models.CharField(choices=[('101', '101동'), ('102', '102동'), ('103', '103동'), ('104', '104동'), ('105', '105동')], default='101', max_length=10, verbose_name='동')),
                ('ho', models.CharField(choices=[('101', '101호'), ('102', '102호'), ('201', '201호'), ('202', '202호'), ('301', '301호'), ('302', '302호'), ('401', '401호'), ('402', '402호'), ('501', '501호'), ('502', '502호'), ('601', '601호'), ('602', '602호'), ('701', '701호'), ('702', '702호'), ('801', '801호'), ('802', '802호'), ('901', '901호'), ('902', '902호'), ('1001', '1001호'), ('1002', '1002호')], default='101', max_length=5, verbose_name='호수')),
                ('place', models.CharField(choices=[('거실', '거실'), ('안방', '안방'), ('주방', '주방'), ('방1', '방1'), ('방2', '방2')], default='거실', max_length=10, verbose_name='소리 녹음 장소')),
                ('value', models.FloatField(null=True, verbose_name='데시벨 측정 값')),
                ('file_name', models.CharField(max_length=40, verbose_name='녹음파일 명')),
                ('sound_file', models.FileField(null=True, upload_to='sound_file/%Y_%m_%d', verbose_name='실제 파일 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='녹음파일 생성일')),
            ],
        ),
        migrations.CreateModel(
            name='Sound_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dong', models.CharField(choices=[('101', '101동'), ('102', '102동'), ('103', '103동'), ('104', '104동'), ('105', '105동')], default='101', max_length=10, verbose_name='동')),
                ('ho', models.CharField(choices=[('101', '101호'), ('102', '102호'), ('201', '201호'), ('202', '202호'), ('301', '301호'), ('302', '302호'), ('401', '401호'), ('402', '402호'), ('501', '501호'), ('502', '502호'), ('601', '601호'), ('602', '602호'), ('701', '701호'), ('702', '702호'), ('801', '801호'), ('802', '802호'), ('901', '901호'), ('902', '902호'), ('1001', '1001호'), ('1002', '1002호')], default='101', max_length=5, verbose_name='호수')),
                ('place', models.CharField(choices=[('거실', '거실'), ('안방', '안방'), ('주방', '주방'), ('방1', '방1'), ('방2', '방2')], default='거실', max_length=10, verbose_name='센서 설치 장소')),
                ('value', models.FloatField(verbose_name='데시벨 측정 값')),
                ('created_at', models.DateTimeField(verbose_name='측정 시간')),
            ],
        ),
        migrations.CreateModel(
            name='Sound_Level_Verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dong', models.CharField(choices=[('101', '101동'), ('102', '102동'), ('103', '103동'), ('104', '104동'), ('105', '105동')], default='101', max_length=10, verbose_name='동')),
                ('ho', models.CharField(choices=[('101', '101호'), ('102', '102호'), ('201', '201호'), ('202', '202호'), ('301', '301호'), ('302', '302호'), ('401', '401호'), ('402', '402호'), ('501', '501호'), ('502', '502호'), ('601', '601호'), ('602', '602호'), ('701', '701호'), ('702', '702호'), ('801', '801호'), ('802', '802호'), ('901', '901호'), ('902', '902호'), ('1001', '1001호'), ('1002', '1002호')], default='101', max_length=5, verbose_name='호수')),
                ('place', models.CharField(choices=[('거실', '거실'), ('안방', '안방'), ('주방', '주방'), ('방1', '방1'), ('방2', '방2')], default='거실', max_length=10, verbose_name='센서 설치 장소')),
                ('value', models.FloatField(null=True, verbose_name='데시벨 측정 값')),
                ('created_at', models.DateTimeField(null=True, verbose_name='측정 시간')),
                ('sound_type', models.CharField(choices=[('충격음', '충격음'), ('가구끄는소리', '가구끄는소리'), ('진공청소기', '진공청소기'), ('악기소리', '악기소리'), ('반려동물', '반려동물')], default='발걸음소리', max_length=30, verbose_name='소음 종류')),
                ('file_name', models.CharField(max_length=40, null=True, verbose_name='녹음 파일 명')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성 일시')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='수정 일시')),
                ('author', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('community_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.communityboard')),
            ],
        ),
        migrations.CreateModel(
            name='ComplainBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='민원 제목')),
                ('content', models.TextField(verbose_name='민원 내용')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성 일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.complainboard')),
            ],
        ),
    ]
