# Generated by Django 4.1.7 on 2023-08-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='communityboard',
            name='author',
        ),
        migrations.RemoveField(
            model_name='communityboard',
            name='like',
        ),
        migrations.RemoveField(
            model_name='complainboard',
            name='author',
        ),
        migrations.DeleteModel(
            name='NoticeBoard',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='community_board',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='CommunityBoard',
        ),
        migrations.DeleteModel(
            name='ComplainBoard',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
